config/routes.rb
Rails.application.routes.draw do
  resources :messages
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "dashboard#index"
  get '/dashboard', to:'dashboard#index', as: :dashboard
  post '/newanswer', to:'dashboard#newanswer',  as: :newanswer
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  scope :active, -> { where("display_date < curdate()") } 
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :partners, class_name: "User", foreign_key: "partner_id", required: false                             
  belongs_to :partner, class_name: "User", required: false  
  has_many :answers
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @partner = current_user.partner
  end

  def newanswer
    @answer = Answer.new(newanswer_params)
    @answer.user = current_user

    respond_to do |format|
      if @answer.save
        format.html { render action: "index" }
        format.json { render json: @answer, status: :created, location: @answer }
      else
        format.html { render action: "index" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def newanswer_params
      params.require(:answer).permit(:value, :question_id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = current_user.partner.messages.active
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @message.user = current_user

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:content, :display_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/dashboard/index.html.erb
<h1>dashboard</h1>
<label>Partner:</label> <%= current_user.partner.name %> <br/>
<ul class="nav nav-pills nav-fill" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="me-tab" data-toggle="tab" href="#me" role="tab" aria-controls="me" aria-selected="true">
      <%= current_user.name %>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="partner-tab" data-toggle="tab" href="#partner" role="tab" aria-controls="partner" aria-selected="false">
      <%= current_user.partner.name %>
    </a>
  </li>
</ul>
<br />
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="me" role="tabpanel" aria-labelledby="me-tab">
    <% Question.all.each do |question| %>
      <div class="card">
        <div class="card-body">
          <div>
            <label><strong><%= question.name %></strong></label>
            <ul class="list-group">
              <% question.answers.where(user: current_user).each do |answer| %>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                  <%= answer.value %>
                  <span class="badge badge-primary badge-pill"> <%= answer.id %> </span>
                </li>
              <% end %>
            </ul>
          </div>
          <br />
          <div>
            <%= simple_form_for(Answer.new, url: newanswer_path) do |f| %>
              <%= f.hidden_field :question_id, value: question.id %>
              <%= f.input :value %> 
              <%= f.submit :submit %>
            <% end %>
          </div>
        </div>
      </div>
      <br />
    <% end %>
  </div>
  <div class="tab-pane fade" id="partner" role="tabpanel" aria-labelledby="partner-tab">
    <% Question.all.each do |question| %>
      <div class="card">
        <div class="card-body">
          <div>
            <label><strong><%= question.name %></strong></label>
            <ul class="list-group">
              <% question.answers.where(user: current_user.partner).each do |answer| %>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                  <%= answer.value %>
                  <span class="badge badge-primary badge-pill"> <%= answer.id %> </span>
                </li>
              <% end %>
            </ul>
          </div>
          <br />
          <div>
            <%= simple_form_for(Answer.new, url: newanswer_path) do |f| %>
              <%= f.hidden_field :question_id, value: question.id %>
              <%= f.input :value %> 
              <%= f.submit :submit %>
            <% end %>
          </div>
        </div>
      </div>
      <br />
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <a class="navbar-brand" href="/">RelationshipApp</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <% if user_signed_in? %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Lists', root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Messages', messages_path, class: 'nav-link' %>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.name %>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to 'Profile', edit_user_registration_path, class: 'dropdown-item' %>
            <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
          </div>
        </li>

      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RelationshipApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render(:partial => "layouts/navbar") %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container"><%= yield %></div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for(@message) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :content %>
  </div>

  <div class="form-inputs">
    <%= f.input :display_date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
<!--       <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.content %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="#">Features</a>
      <a class="nav-item nav-link" href="#">Pricing</a>
      <a class="nav-item nav-link disabled" href="#">Disabled</a>
    </div>
  </div>
</nav>